id: status-schema-change
title: "Status Schema Change"
status: ready-to-ship
owner: "Steins Z"
priority: P1
teams: []
tags: []
created: "2026-03-05"
updated: "2026-03-05"
progress: 100
# target_release: ""
# blocked_by: []
